<a href="https://colab.research.google.com/github/ajay10258/placement/blob/master/placement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#_classification_

#importing

In [1]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('/content/Placement_Data_Full_Class.csv')
dataset

sl_no gender  ssc_p    ssc_b  ...  specialisation  mba_p      status    salary
0        1      M  67.00   Others  ...          Mkt&HR  58.80      Placed  270000.0
1        2      M  79.33  Central  ...         Mkt&Fin  66.28      Placed  200000.0
2        3      M  65.00  Central  ...         Mkt&Fin  57.80      Placed  250000.0
3        4      M  56.00  Central  ...          Mkt&HR  59.43  Not Placed       NaN
4        5      M  85.80  Central  ...         Mkt&Fin  55.50      Placed  425000.0
..     ...    ...    ...      ...  ...             ...    ...         ...       ...
210    211      M  80.60   Others  ...         Mkt&Fin  74.49      Placed  400000.0
211    212      M  58.00   Others  ...         Mkt&Fin  53.62      Placed  275000.0
212    213      M  67.00   Others  ...         Mkt&Fin  69.72      Placed  295000.0
213    214      F  74.00   Others  ...          Mkt&HR  60.23      Placed  204000.0
214    215      M  62.00  Central  ...          Mkt&HR  60.22  Not Placed       NaN

[215 rows x 15 columns]

#splitting

as we are perdicting the placement ,i have not taken the salary coloumn of the data.So salary is not required for analysing the data

In [2]:
x = dataset.iloc[:,[4,7,9,10,8,12]].values
y = dataset.iloc[:,-2].values


In [3]:
x

array([[91.0, 58.0, 'No', 55.0, 'Sci&Tech', 58.8],
       [78.33, 77.48, 'Yes', 86.5, 'Sci&Tech', 66.28],
       [68.0, 64.0, 'No', 75.0, 'Comm&Mgmt', 57.8],
       ...,
       [67.0, 73.0, 'Yes', 59.0, 'Comm&Mgmt', 69.72],
       [66.0, 58.0, 'No', 70.0, 'Comm&Mgmt', 60.23],
       [58.0, 53.0, 'No', 89.0, 'Comm&Mgmt', 60.22]], dtype=object)

In [4]:
y

array(['Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Not Placed',
       'Not Placed', 'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Not Placed',
       'Placed', 'Not Placed', 'Not Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Not Placed', 'Placed', 'Placed',
       'Not Placed', 'Placed', 'Placed', 'Placed', 'Placed', 'Placed',
       'Placed', 'Not Placed', 'Placed', 'Placed', 'Placed', 'Not Placed',
  

#importing

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
dataset['degree_t'].unique()

array(['Sci&Tech', 'Comm&Mgmt', 'Others'], dtype=object)

converting char to unique number,we use label encoding

#label encoding

In [6]:
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [2,4])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

#splitting

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

#scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,4:] = sc.fit_transform(x_train[:,4:])
x_test[:,4:] = sc.transform(x_test[:,4:])

#importing


In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import  LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix

In [10]:
r_reg=RandomForestClassifier(n_estimators=200)
l_reg=LogisticRegression()
d_reg=DecisionTreeClassifier()
k_reg=KNeighborsClassifier()
s_reg=SVC()

#fitting

In [11]:
r_reg.fit(x_train,y_train)
l_reg.fit(x_train,y_train)
d_reg.fit(x_train,y_train)
k_reg.fit(x_train,y_train)
s_reg.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#predicting

In [12]:
r_pred=r_reg.predict(x_test)
l_pred=l_reg.predict(x_test)
d_pred=d_reg.predict(x_test)
k_pred=k_reg.predict(x_test)
s_pred=s_reg.predict(x_test)
cm = confusion_matrix(y_test,k_pred)
print(cm)

[[ 6 10]
 [ 2 25]]


#displaying data

In [13]:
from sklearn.metrics import accuracy_score
r=accuracy_score(y_test,r_pred)
l=accuracy_score(y_test,l_pred)
d=accuracy_score(y_test,d_pred)
k=accuracy_score(y_test,k_pred)
s=accuracy_score(y_test,s_pred)
print('RandomForestClassifier=',r)
print('LogisticRegression=',l)
print('DecisionTreeClassifier=',d)
print('KNeighborsClassifier',k)
print('SVC=',s)

RandomForestClassifier= 0.813953488372093
LogisticRegression= 0.8372093023255814
DecisionTreeClassifier= 0.7441860465116279
KNeighborsClassifier 0.7209302325581395
SVC= 0.7906976744186046


here more accuary is shown in LogisticRegression classifier.so this is the best model for the data




#confusion matrix

In [14]:
print('confusion_matrix',cm)

confusion_matrix [[ 6 10]
 [ 2 25]]


#_regression_

#importing

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [16]:
m_reg=LinearRegression()
p_reg=LinearRegression()
d_reg=DecisionTreeRegressor()
r_reg=RandomForestRegressor()


#polynomial

In [17]:
x_poly=PolynomialFeatures(degree=2)
x_poly=x_poly.fit_transform(x_train)

In [18]:
m_reg.fit(x_train,y_train)
p_reg.fit(x_poly,y_train)
d_reg.fit(x_train,y_train)
r_reg.fit(x_train,y_train)


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

#predicting data

In [19]:
temp=PolynomialFeatures(degree=2)
temp=temp.fit_transform(x_test)
m_pred=m_reg.predict(x_test)
p_pred=p_reg.predict(temp)
d_pred=d_reg.predict(x_test)
r_pred=r_reg.predict(x_test)

#displaying data

In [20]:
from sklearn.metrics import r2_score
m =r2_score(y_test,m_pred)
p =r2_score(y_test,p_pred)
d =r2_score(y_test,d_pred)
r =r2_score(y_test,r_pred)
print("LinearRegression=",m)
print("PolynomialFeatures=",p)
print("DecisionTreeRegressor=",d)
print("RandomForestRegressor=",r)

LinearRegression= 0.36271724383712556
PolynomialFeatures= 0.07363952447970723
DecisionTreeRegressor= 0.10416666666666685
RandomForestRegressor= 0.36161921296296307


here LinearRegression shows more accuary than other models